name: integration

on:
  push:
    branches: [ master ]

jobs:
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v2.0.0
    secrets: inherit
  deploy:
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.0.0
    needs: [publish]
    secrets: inherit
    with:
      DEPLOY_ENV: dev
      DEPLOY_APP: ${{ github.event.repository.name }}
      DEPLOY_VERSION: ${{ github.ref_name }}
      DEPLOY_SUBDOMAIN: hyperchain
