name: release

on:
  push:
    tags: [ v* ]

jobs:
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-ecr.yml@v2.3.1
    secrets: inherit
  deploy:
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.3.1
    needs: [publish]
    secrets: inherit
    with:
      DEPLOY_ENV: stg #TODO change to prd
      DEPLOY_APP: ${{ github.event.repository.name }}
      DEPLOY_TAG: ${{ github.ref_name }}
      DEPLOY_SUBDOMAIN: hyperchain
